Fix git diff paging

diff --git a/replace-in-repo/action.yaml b/replace-in-repo/action.yaml
--- a/replace-in-repo/action.yaml
+++ b/replace-in-repo/action.yaml
@@ -54,13 +54,13 @@ runs:
       run: |-
         if [[ -n $(git status --porcelain) ]]; then
           echo "Uncommited changes detected:"
-          git diff
+          git --no-pager diff
           echo
           if [[ ${{ inputs.reset }} == 'true' ]]; then
             echo "Resetting uncommitted changes."
             git reset --hard
           else
-            echo "Error: Aborting to prevent committing and pushing those changes. Turn on `reset` option to discard changes."
+            echo "Error: Aborting to prevent committing and pushing those changes. Turn on `reset` option to discard changes." >&2
             exit 1
           fi
         fi
